name: Test/Publish

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -e .

      - name: Test
        run: pytest

      - name: Run Coverage
        if: "${{ matrix.python-version == '3.8' }}"
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
        run: coveralls

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/0.1' }}"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Configure twine
        run: |
          cat << EOF > ~/.pypirc
          [pypi]
          username = __token__
          password = ${{ secrets.PYPI_DEPLOY_TOKEN }}
          EOF

      - name: Publish to PyPI
        run: twine upload dist/*
